name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
      - run: yarn lint:check
      - run: yarn build
      - run: yarn test
